### ISSUE TITLE
Captcha Verification failed.

### ISSUE THREAD

**Issue by marvelhoax** [jgillich/faststack#40] opened 2017-03-14 19:04 UTC
![screenshot from 2017-03-15 00-19-36](https://cloud.githubusercontent.com/assets/26195765/23917827/b3b8aec8-0916-11e7-9b8c-2f4a34d42eb3.png)
Captcha verification failed for every distro... Please Update it.

**Comment by jgillich** [comment] 2017-03-14 20:13
Dupe of #39

**Closed as completed** 2017-03-14 20:13 UTC
